#use_frameworks!
platform :ios, "8.0"

target 'SHWNLSClientSDK_Example' do
  pod 'SHWNLSClientSDK', :path => '../'

  target 'SHWNLSClientSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
